services:
  database:
    build:
      dockerfile: docker/mariadb/Dockerfile
    container_name: solidary-food-distribution-database
    networks:
      - app-network
    environment:
      MARIADB_ROOT_PASSWORD: root
      #MARIADB_USER: root
      #MARIADB_PASSWORD: root
      MARIADB_DATABASE: sofodi
    ports:
      - "3306:3306"

  # PHP Service
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: solidary-food-distribution-php
    volumes:
      - ./web:/var/www/public
      - ./web:/var/www/web
      - ./modules:/var/www/modules
      - ./lib:/var/www/lib
      - ./templates:/var/www/templates
      - ./config:/var/www/config
    networks:
      - app-network
    environment:
      PHP_IDE_CONFIG: serverName=Docker # For Xdebug

  # Nginx Service
  nginx:
    build:
      dockerfile: docker/nginx/Dockerfile
    container_name: solidary-food-distribution-nginx
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge          # Standard Docker network type